/** Copy belongs to the batch presentation; calculation IDs and persisted records stay unchanged. */
export const multiPlanAiCopy = {
  en: {
    title: 'Multi-plan AI', project: 'Project', close: 'Close', newBatch: 'New batch', batches: 'Saved batches',
    steps: ['Select plans', 'Choose calculations', 'Review & start', 'Processing & results'],
    plansTitle: 'Which plans would you like to analyze?', plansIntro: 'Select whole PDF documents, or expand a document to choose specific pages.',
    documents: 'documents', pages: 'pages', page: 'Page', selected: 'selected', selectedPages: 'selected pages',
    allPages: 'All pages selected', somePages: 'pages selected', noPages: 'Not selected', selectDocument: 'Select all pages in',
    expand: 'Show pages', collapse: 'Hide pages', selectAll: 'Select all', clear: 'Clear selection',
    noDocuments: 'No imported PDFs are available.', noDocumentsHint: 'Import PDF plans into this project, then return here.',
    next: 'Continue', back: 'Back', editPlans: 'Edit plans', editCalculations: 'Edit calculations',
    calculationsTitle: 'What would you like to measure?', calculationsIntro: 'Choose the quantities you need. You can configure finish work after reviewing the detected spaces.',
    geometry: 'Geometry measurements', finishes: 'Finish quantities', area: 'Floor area', perimeter: 'Room perimeter',
    flooring: 'Flooring', cladding: 'Wall cladding', skirting: 'Skirting',
    areaDescription: 'Measure the floor area of accepted Rooms.', perimeterDescription: 'Measure the boundary length of accepted Rooms.',
    flooringDescription: 'Use flooring work items and their waste settings.',
    claddingDescription: 'Use wall-cladding items with an explicit height and opening deductions.',
    skirtingDescription: 'Use skirting items with perimeter, door deductions and waste settings.',
    calibrationNote: 'Physical quantities require page calibration. Finishes also require work items on accepted Rooms; nothing is assigned automatically.',
    reviewTitle: 'Review your batch', reviewIntro: 'Check the pages and measurements before confirming. New page analysis can incur API charges.',
    selectedPlans: 'Selected documents', measurements: 'Selected calculations', scopePages: 'Pages in this batch',
    reusable: 'Existing AI results', newRequests: 'New paid requests', inProgress: 'Existing request in progress',
    estimate: 'Estimated API cost', notGuaranteed: 'Indicative range · not guaranteed',
    historical: 'Based on local recorded costs, or the documented $0.076/page average when no local observations exist. Actual charges and spending reservations may be higher.',
    confirmation: 'Confirming sends the selected pages needing new inference as images to OpenAI for paid processing. Provider retention rules apply. Existing spending limits still apply.',
    confirm: 'Confirm paid requests & start', confirmResume: 'Confirm paid requests & resume', useResults: 'Continue with existing results',
    afterStart: 'Next: review detected spaces, approve valid geometry, then calibrate and configure quantities.',
    resultsTitle: 'Processing & results', resultsIntro: 'Pages are analyzed one at a time. Open a completed page to review spaces in the existing AI workspace.',
    processing: 'Processing', queued: 'Queued', completed: 'Completed', failed: 'Failed', awaitingReview: 'Awaiting review',
    partial: 'Partially reviewed', reviewed: 'Reviewed', approved: 'accepted Rooms', reviewLoading: 'Loading review state',
    paused: 'Scheduling paused', finished: 'Detection finished', activePage: 'Currently processing',
    stop: 'Stop after current page', stopping: 'Stopping after current page', resume: 'Review & resume',
    stopNote: 'The current request will finish. Stopping prevents the next queued page from starting.',
    pausedNote: 'Queued pages stay paused until you review and confirm the remaining scope.',
    review: 'Review spaces', openPage: 'Open page', configure: 'Configure quantities',
    calibration: 'Awaiting calibration', configuration: 'Awaiting quantity configuration', ready: 'Ready for selected quantities',
    empty: 'No accepted Rooms', changed: 'Source PDF changed or document removed', detectionPending: 'Awaiting AI detection',
    pageDetails: 'Room details & measurements', selectRoom: 'Select Room', roomHint: 'Select a Room, then open its details using the existing Room controls.',
    quantities: 'Selected-page quantity summary', acceptedOnly: 'Only accepted Rooms contribute. Uncalibrated or unconfigured quantities remain pending.',
    pending: 'Pending', order: 'to order', projectReport: 'Project quantity reports', projectReportHint: 'Existing project reports include all plans.',
    failureNote: 'Failed requests are not retried automatically. Review the error before deliberately creating another paid batch.',
    noBatches: 'No batches yet', noBatchesHint: 'Choose your plans and measurements to start your first batch.',
    returnToPlan: 'Return to project', loading: 'Reading imported PDF documents…', working: 'Preparing your selection…',
    loadingResults: 'Loading saved results…', selectAtLeast: 'Select at least one page to continue.', chooseAtLeast: 'Choose at least one calculation to continue.',
    batch: 'Batch', openBatch: 'Open batch', selectionSummary: 'Selection summary', costDetails: 'How this estimate is calculated',
  },
  he: {
    title: 'AI למספר תוכניות', project: 'פרויקט', close: 'סגירה', newBatch: 'אצווה חדשה', batches: 'אצוות שמורות',
    steps: ['בחירת תוכניות', 'בחירת חישובים', 'בדיקה והתחלה', 'עיבוד ותוצאות'],
    plansTitle: 'אילו תוכניות לנתח?', plansIntro: 'בחרו מסמכי PDF שלמים, או פתחו תוכנית כדי לבחור עמודים מסוימים.',
    documents: 'מסמכים', pages: 'עמודים', page: 'עמוד', selected: 'נבחרו', selectedPages: 'עמודים שנבחרו',
    allPages: 'כל העמודים נבחרו', somePages: 'עמודים נבחרו', noPages: 'לא נבחר', selectDocument: 'בחירת כל העמודים בתוכנית',
    expand: 'הצגת עמודים', collapse: 'הסתרת עמודים', selectAll: 'בחירת הכול', clear: 'ניקוי הבחירה',
    noDocuments: 'אין קובצי PDF מיובאים בפרויקט.', noDocumentsHint: 'ייבאו תוכניות PDF לפרויקט וחזרו לכאן.',
    next: 'המשך', back: 'חזרה', editPlans: 'עריכת תוכניות', editCalculations: 'עריכת חישובים',
    calculationsTitle: 'מה תרצו למדוד?', calculationsIntro: 'בחרו את הכמויות הנחוצות. את עבודות הגמר ניתן להגדיר לאחר בדיקת החללים שזוהו.',
    geometry: 'מדידות גאומטריות', finishes: 'כמויות גמר', area: 'שטח רצפה', perimeter: 'היקף חדר',
    flooring: 'ריצוף', cladding: 'חיפוי קירות', skirting: 'פנלים',
    areaDescription: 'מדידת שטח הרצפה בחדרים שאושרו.', perimeterDescription: 'מדידת אורך גבול החדרים שאושרו.',
    flooringDescription: 'חישוב לפי עבודות הריצוף והגדרות הפחת שלהן.',
    claddingDescription: 'חישוב לפי עבודות חיפוי עם גובה מפורש וניכוי פתחים.',
    skirtingDescription: 'חישוב לפי עבודות פנלים, היקף, ניכוי דלתות ופחת.',
    calibrationNote: 'כמויות במטרים ובמ״ר מחייבות כיול עמוד. כמויות גמר מחייבות גם פריטי עבודה בחדרים שאושרו; דבר אינו משויך אוטומטית.',
    reviewTitle: 'בדיקת האצווה לפני ההתחלה', reviewIntro: 'בדקו את העמודים והחישובים לפני האישור. ניתוח עמוד חדש עשוי להיות כרוך בחיוב API.',
    selectedPlans: 'מסמכים שנבחרו', measurements: 'חישובים שנבחרו', scopePages: 'עמודים באצווה',
    reusable: 'תוצאות AI קיימות', newRequests: 'בקשות חדשות בתשלום', inProgress: 'בקשה קיימת בעיבוד',
    estimate: 'עלות API משוערת', notGuaranteed: 'טווח משוער · ללא התחייבות',
    historical: 'מבוסס על עלויות שנשמרו מקומית, או על הממוצע המתועד של $0.076 לעמוד בהיעדר נתונים מקומיים. החיוב בפועל ושריון התקציב עשויים להיות גבוהים יותר.',
    confirmation: 'האישור שולח את העמודים שנבחרו וזקוקים לניתוח חדש כתמונות ל־OpenAI לעיבוד בתשלום. חלים כללי שמירת המידע של הספק. מגבלות התקציב הקיימות ממשיכות לחול.',
    confirm: 'אישור בקשות בתשלום והתחלה', confirmResume: 'אישור בקשות בתשלום והמשך', useResults: 'המשך עם תוצאות קיימות',
    afterStart: 'השלב הבא: בדיקת החללים, אישור גאומטריה תקינה, ואז כיול והגדרת כמויות.',
    resultsTitle: 'עיבוד ותוצאות', resultsIntro: 'העמודים מנותחים בזה אחר זה. פתחו עמוד שהושלם כדי לבדוק חללים בסביבת בדיקת ה־AI הקיימת.',
    processing: 'בעיבוד', queued: 'בתור', completed: 'הושלם', failed: 'נכשל', awaitingReview: 'ממתין לבדיקה',
    partial: 'נבדק חלקית', reviewed: 'נבדק', approved: 'חדרים שאושרו', reviewLoading: 'טעינת מצב הבדיקה',
    paused: 'התזמון מושהה', finished: 'הזיהוי הסתיים', activePage: 'כעת בעיבוד',
    stop: 'עצירה אחרי העמוד הנוכחי', stopping: 'עצירה אחרי העמוד הנוכחי', resume: 'בדיקה והמשך',
    stopNote: 'הבקשה הנוכחית תסתיים. העצירה מונעת התחלת עיבוד של העמוד הבא בתור.',
    pausedNote: 'העמודים שבתור נשארים מושהים עד לבדיקה ולאישור של ההיקף שנותר.',
    review: 'בדיקת חללים', openPage: 'פתיחת עמוד', configure: 'הגדרת כמויות',
    calibration: 'ממתין לכיול', configuration: 'ממתין להגדרת כמויות', ready: 'מוכן לכמויות שנבחרו',
    empty: 'אין חדרים שאושרו', changed: 'קובץ המקור השתנה או שהתוכנית הוסרה', detectionPending: 'ממתין לזיהוי AI',
    pageDetails: 'פרטי חדרים ומדידות', selectRoom: 'בחירת חדר', roomHint: 'בחרו חדר, ואז פתחו את פרטיו דרך בקרות החדר הקיימות.',
    quantities: 'סיכום כמויות בעמודים שנבחרו', acceptedOnly: 'רק חדרים שאושרו משתתפים בחישוב. כמויות ללא כיול או הגדרה נשארות בהמתנה.',
    pending: 'ממתין', order: 'להזמנה', projectReport: 'דוחות כמויות של הפרויקט', projectReportHint: 'דוחות הפרויקט הקיימים כוללים את כל התוכניות.',
    failureNote: 'בקשות שנכשלו אינן נשלחות שוב אוטומטית. בדקו את השגיאה לפני יצירת אצווה נוספת בתשלום.',
    noBatches: 'עדיין אין אצוות', noBatchesHint: 'בחרו תוכניות וחישובים כדי להתחיל את האצווה הראשונה.',
    returnToPlan: 'חזרה לפרויקט', loading: 'קריאת מסמכי PDF מיובאים…', working: 'הכנת הבחירה…',
    loadingResults: 'טעינת תוצאות שמורות…', selectAtLeast: 'בחרו לפחות עמוד אחד כדי להמשיך.', chooseAtLeast: 'בחרו לפחות חישוב אחד כדי להמשיך.',
    batch: 'אצווה', openBatch: 'פתיחת אצווה', selectionSummary: 'סיכום הבחירה', costDetails: 'כיצד מחושב האומדן',
  },
};
